#ifndef MBEDTLS_CONFIG_TEST_H
#define MBEDTLS_CONFIG_TEST_H

#define MBEDTLS_MD_LIGHT
#define MBEDTLS_PSA_CRYPTO_C
//#define MBEDTLS_PSA_CRYPTO_CLIENT
#define MBEDTLS_PSA_CRYPTO_CONFIG

#endif /* MBEDTLS_CONFIG_TEST_H */
